apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: devopslab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: devopslab
spec:
  serviceName: postgres
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:18

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: devopslab

            - name: POSTGRES_USER
              value: devopslab_user

            - name: POSTGRES_PASSWORD
              value: DevOpsLab@123

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U devopslab_user -d devopslab
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U devopslab_user -d devopslab
            initialDelaySeconds: 15
            periodSeconds: 10

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devopslab

spec:
  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432