apiVersion: v1
kind: Pod
metadata:
  name: oom-demo
  namespace: k8slab

spec:
  containers:
  - name: memory-test
    image: python:3.12-alpine

    command:
      - python

    args:
      - -c
      - |
       data = [] 
       while True:
        data.append("x" * 1024 * 1024)

    resources:
      requests:
        memory: 32Mi

      limits:
        memory: 64Mi
