apiVersion: v1
kind: Pod
metadata:
  name: persistent-pod
  namespace: k8slab

spec:
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
      - name: persistent-data
        mountPath: /data


  volumes:
    - name: persistent-data
      persistentVolumeClaim:
        claimName: pvc-lab