apiVersion: v1
kind: Pod
metadata:
  name: probe-demo
  namespace: k8slab
  labels:
    app: probe-demo

spec:
  containers:
  - name: nginx
    image: nginx:alpine

    ports:
    - containerPort: 80

    startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 30
      periodSeconds: 2

    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 2
      periodSeconds: 5

    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 2
      periodSeconds: 5



