apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lab

spec:
  capacity:
    storage: 1Gi

  accessMode:
  - ReadWriteOnce

  persistentVolumeReclaimPolicy: delete
  storageClassName: manual
  hostPath:
    path: /tmp/k8slabdata