apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lab
  namespace: k8slab
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual

  resources:
    requests:
      storage: 1Gi